proxy:
  endpoints:
    - name: webservices
      port: 4000
      remote:
        check_after: 5
        endpoints:
          - url: "http://webservices.oorsprong.org"

rules:
  "webservices":
    "GET *":
      on_request: !include rules/on_request.py

    "POST *":
      on_response: !include rules/on_response.py
