proxy:
  endpoints:
    - name: store
      port: 4000
      remote:
        check_after: 5
        endpoints:
          - url: "http://yourstore.com"

rules:
  "store":
    "GET /api/products":
      on_request: !include rule.py
