[tool.poetry]
name = "mock-api"
version = "0.1.0"
description = ""
authors = ["Anonymous"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.12"
harp-proxy = "^0.7.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
